### ISSUE TITLE
Add Support for ToEntityReference Method

### ISSUE THREAD

**Issue by sdaniil** [kip-dk/angular-xrmservice#20]
Please add ToEntityReference method to Entity class. 
To get an entity reference from entity instance.

**Comment by kip-dk** [comment]
This is not a simple task. In C# on the SDK, the method is there, because it is simple and consistant. In web api it is different, because for an EntityReference to be usedfull, you need to know the context, because it is references by the relationship schema name, not the simple combination of a logical entity name + and id.

Ex. transforming a campaign entity to an entity ref. will require the code to know in what context the entity reference should be used.  If it is the regardingobjectid on a campaignresponse, it has one name, if it is the sourcecampaign on a lead, it has another name.

That is why the crmcontext service is generating EntityReference fields from the metadata, so you basically only need to deal with the id of a ref.

so if you have an entity with a ref. to another entity, you only need to deal with the id, but you must ensure that the entity field is defined with the correct schemaname. In such case you can simply write


myaccount.primarycontactid.id = mycontact.id

you do not need to convert the mycontact to an entity ref.

**Comment by sdaniil** [comment]
Thanks for your reply 😊

Could we just implement the following:
1)	Extra constructor for EntityReferance class, ex.: constructor(logicalname: string, ) 
2)	Method ToEntityReferance inside Entity class

Let’s say that you had retrieved 1000 Account entities with help of WebApi and you would like to export/process only logicalName and entityId to the file or DataTable.  It will be much more easier to use it like this:

	this.exportAccounts = […this.exportAccounts, ...this.webApiAccounts.value.map(entity => entity.ToEntityReferance() )];

Here is how the ToEntityReference method implemented inside Microsoft.Xrm.Sdk.dll (Latest version):

    /// <summary>Gets an entity reference for this entity instance.</summary>
    /// <returns>Type: <see cref="T:Microsoft.Xrm.Sdk.EntityReference" />The entity reference for the entity.</returns>
    public EntityReference ToEntityReference()
    {
      return new EntityReference(this.LogicalName, this.Id)
      {
        RowVersion = this.RowVersion
      };
    }

**Comment by kip-dk** [comment]
EntityReference in C# SDK, is not the same as EntityReference in this typescript based framework.

When working with C# SDK, fields are assigned on the form  myobj.regardingobjectid = new EntityReference( anid,  entitylogicalname)  and the EntityReference is as such consistant cross any entity.

I Webapi, and entity reference is assigned on the form

myobj["opdata.bind@{schemaname on the reference}"] = '/pluralnameonentity(id)'

So in C# you need to know id and logicalname of an entity to assign a navigation property. 

In Web api, you need to know  the schemaname of the navigationproperty (it is NOT the same as the field name), and the plural name of the entity, and that is what EntityReference is representing in the Kipon.XrmService.

The framework did lack of good facilities to create usable EntityReferences from an entity instance, so that has been added in version 2.2.18. If you need to convert an entity to a ref, for the purpose of reporting only, you can now do so by  myentity.ToEntityReference(), but if you need to assign a navigation property in another entity, you must parse the associationpropertyname,

ex. regardingobjectid on campaignreponse, can now be assigned from an instance of a campaign in the way:

myresponse.regardingobjectid = campaign.ToEntityReference('regardingobjectid_campaign')
