### ISSUE TITLE
Support for functions?

### ISSUE THREAD

**Issue by ChristianCRM** [kip-dk/angular-xrmservice#5]
Great tool so far. I have the need to use functions in CRM. Does it currently support them or is it easy enough to implement?

**Comment by kip-dk** [comment]
Hi ChristianCRM. 

First thanks for the feedback.

Not 100% sure what you mean with "functions", are you talking abount Actions, because they are supported:

inject an xrmContextService into your angular service/component, and use the action method to
call a crm action.

XrmContextService.action(name: string, data:any, instance?: Entity): Observable

name is the name of the action

data is a json representation of whatever paramer you action needs. Due to the generic nature of this interface, you have to look into the Dynamics 365 SDK to know excatly how this looks, finally parse an instance of your entity, if the action needs one, ex SetStateRequest. 

The observable<any> will return the json Response of the action, but naturally it does not know what type of cat that is. 

If i misunderstood the question, do not hesetate to ask again.

**Comment by ChristianCRM** [comment]
Hi kip-dk,

Thank you for your prompt response. The reason why I need functions is that there is a "WhoAmI" function that returns the organization id as well as the user id in one call.

I have been playing around with the tool for the last 15 mins and I can see that this call is already implemented, however I can see the returned json in the network tab but when I tap into the observable I get an empty object or undefined.

The method I'm currently using is getCurrentKey, which I gues has nothing to do with the "WhoAmI" and that the latter is used by it indirectly.

Is there a way to expose the "WhoAmI" function without having to write a wrapper? I am currently developing on a on-premise v8.2 environment but the target would be mostly v9+ (currently waiting to get the dev environment v9 up and running).

Should need more information please feel free to ask.

Christian

**Comment by kip-dk** [comment]
The internals of xrmcontextservice and xrmservice is using the whoami function to actually figure out who you are, but the result is not currently exposed in a "public api" of the service. I need to consider where to put such thing before adding it. It could belong to the contextService and xrmContextService if it supports a total generic facility in crm to call requests that does not have a body, but let me first look into the generic nature of your request. If this pattern applies to whoami() only, then i would rather add it to a specialized service like a me() method on the XrmSecurityService on the KiponXrmSecurityModule. I will get back on this ASAP. Happy XRM coding. :-)

**Comment by ChristianCRM** [comment]
That would be great! Thank you.

**Comment by kip-dk** [comment]
I have been looking into function, and that is absolutly dueable (and makes a lot of sence to add), and the requirement does belong into xrmservice (where it will be a very simple string map, you have to do all the hard work of building a correct url, but the framework will add headers and so),   and a xrmcontextservice, that adds more help in regards to transforming parameters from into correct structure from a json object, and create the correct bound part of the uri from an entity instance. From the dynamics api i can se that functions by definition has no side effects(does not chance anything in the backend), so functions will not be supported in transactions. (they do not make sence there, they would just worsen performance and not add anything). I will update the issue when a version with this is in place. It will only be added to 2.1.x and as such only supported for angular 7 or >.

**Comment by ChristianCRM** [comment]
That's great to hear! Will this be done by next week? It will become critical to have this by next week as I am planning to use this for production software.
Also this will solve the issue #6 as getting the currently logged in user is another common requirement across our applications.

**Comment by kip-dk** [comment]
Hi Christian, - lets keep the issues separate, even though looking from your usecase it looks the same, it is two different issues. Implementing support for totally new parts of the CRM api require a bit of considuration, so it is not executed as fast as bug fix, but i will try to look at it later today, and give you an estimate when i think it can be in place. Functions looks alot like actions (and they are already supported), so i do not think the effort will be that much, however they are differences in the two types of call. Functions uses http-get, and stream parameters as query string parameters on the form (X=@1, Y=@2)?@1=adsf&@2=dfh, while action uses post and stream parameters as the http body in json format.

**Comment by kip-dk** [comment]
As promised a feedback on expected timeline on impl. this. 
For xrmservce (the simple string wrapper imp.) this is very easy to impl. because all the headeck of transforming an object graph into valid parameters it put on the shoulder of the programmer using the framework. As for xrmcontext service, that has the purpose of giving a more natural programmer experience when working with the api, this has proven to be less trivial. 

I do not wish to create a release with the first one only, because my recommendation is not to use it directly, it should be a black box to most programmers, so making a release that encourage to use thatservice would be wrong. So releasing will have to wait until a prober impl. in xrmcontextservice is in place and this will take some time, so do not expect any progess until sometime late august.

If you really need functions, and you are willing to stroggle with the syntax of function parameters (it might be trivial for some cases, ex whoAmI is as simple as can bee, but supporting any is not trivial) i am willing to release a alfa version of the library, that expose the new func( parameters) in the xrmservice.  But it require some time and testing to release it for the xrmcontextservice.

**Comment by kip-dk** [comment]
Version 2.2.3 now support function by the method func(..): Observable<any>. The func api. is very comprehensive when it comes to parsing parameters, so not all scenarios has been tested firmly, however a method has been added to allow any user of the framework to figure out the streaming mechanism them self for specifc types that are currently not supported. Do not hesitate to raise an issue for specific function names and types not currently supported.
