### ISSUE TITLE
getCurrentUserId() does not work in development

### ISSUE THREAD

**Issue by ChristianCRM** [kip-dk/angular-xrmservice#6]
The method **getCurrentUserId** does not point to the configured endpoint (this is only for development).
I have configured my endpoint to be different from localhost but this method tries to execute the api call on localhost and, of course, it fails.

**Comment by kip-dk** [comment]
If you are running your angular inside dynamics 365 (normally as and iframe .. that is how dynamics 365 deploy web resources), the endpoint is the same as the parent form (or the window opener if it is a popup).

if you use ng-serve, then your app is running outside dynamics 365, and the endpoint need to be configurede some how. The easy track is to use proxy configuration if you are using on-premise. The only drawback is that you need to enable basic authentication on your CRM (i actually have a fix on the way, where you do not need this, it will use windows auth. .. but it is not release yet). Otherwise you can use XrmConfigService to configure you end-point while testing. Look at the documentation on the npm site: https://www.npmjs.com/package/kipon-xrmservice in the chapter with title "Local development outside Dynamics 365"

**Comment by kip-dk** [comment]
if you have done all the above, and the concept is actually working, but getCurrentUserId is using wrong endpoint, it might be because you are doing things to early. For development outside CRM (developer mode), current user is resolved by calling "whoami()" on the CRM, but that is async, so it might take a sec. or two before it has populated the result from there into its own state (that normaly comes from the Dynamics 365 context.)

**Comment by ChristianCRM** [comment]
There is no method that allows me to perform the WhoAmI function currently.
Here's what I am doing:

1. Inject the service into the app.component
2. in the constructor make a call to the crm system

if I query any record the tool works fine and the WhoAmI function is called against the right endpoint.
If I execute the getCurrentUserId method, even after the query, the endpoint is wrong.

**Comment by kip-dk** [comment]
that sounds like a bug, i will assume you will get **correct** results when running inside CRM, but when running in developer mode outside, the userid return apparently do not get updated correct from the fake crmcontext, created by the framework.  I will look into that.

**Comment by ChristianCRM** [comment]
Thank you.

I have not yet tried to run it on the system itself, but I will let you know once I do.

**Comment by kip-dk** [comment]
Hi Christian 

this issue has been fixed with version 2.2.2, so try update your npm package for kipon-xrmservice and run again. I fixed the code, that indeed did fall back to localhost:4200 for this specific method, when XrmConfigService was used to resolve dynamics url. This problem would never check in, when deployed under CRM. This is because the framework creates a fake Xrm.Page.Context when running in developermode to support ng serve based development effort.

Thanks a lot for your input. I will close the case. Please open a new case if you still have problems around this issue.

**Comment by ChristianCRM** [comment]
Hi Kip,

Updated the package and tested and it works! Thank you
